[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff]

exclude = [
    "doc",
    ]

[tool.ruff.lint]
ignore = ["F403", "F405"]

[tool.pytest.ini_options]
addopts = "-n auto"

[tool.coverage.run]
omit = [
    "tests/*",
]
